import { useState } from 'react';
import { MapPin, ArrowUpRight, Grid3X3, Layers, Pencil, X, Check } from 'lucide-react';
import Header from '../components/Header';
import { portfolio, profileProjects } from '../data/mockData';
export default function Profile({ user, setUser, notify }) {
 const [tab, setTab] = useState('portfolio');
 const [editing, setEditing] = useState(false);
 const [draft, setDraft] = useState(user);
 return <><Header title="Profilo"/><section className="profile-page"><div className="profile-top"><img className="profile-avatar" src={user.avatar} alt={user.name}/></div>{editing ? <form className="edit-profile" onSubmit={e => { e.preventDefault(); setUser(draft); setEditing(false); notify('Profilo aggiornato'); }}><div className="edit-heading"><h2>Modifica profilo</h2><button type="button" className="icon-button" aria-label="Annulla modifica" onClick={() => setEditing(false)}><X size={20}/></button></div>{[{ key: 'name', label: 'Nome' }, { key: 'profession', label: 'Professione' }, { key: 'city', label: 'Città' }, { key: 'bio', label: 'Bio' }].map(({ key, label }) => <label key={key}>{label}{key === 'bio' ? <textarea value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} required maxLength={250}/> : <input value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} required maxLength={70}/>}</label>)}<button className="primary-button"><Check size={18}/> Salva modifiche</button></form> : <><div className="profile-name"><h1>{user.name}</h1><span>@{user.username}</span></div><p className="profession">{user.profession}</p><p className="bio">{user.bio}</p><div className="profile-links"><span><MapPin size={15}/>{user.city}</span><a href={user.portfolio} target="_blank" rel="noreferrer">Portfolio video<ArrowUpRight size={16}/></a></div><div className="profile-stats"><div><strong>3</strong><span>Progetti</span></div><div><strong>12</strong><span>Collaborazioni</span></div><div><strong>846</strong><span>Follower</span></div></div><button className="edit-button" onClick={() => { setDraft(user); setEditing(true); }}><Pencil size={15}/>Modifica profilo</button></>}
 <div className="profile-tabs" role="tablist" aria-label="Lavori pubblicati"><button id="portfolio-tab" role="tab" aria-selected={tab === 'portfolio'} aria-controls="profile-panel" className={tab === 'portfolio' ? 'active' : ''} onClick={() => setTab('portfolio')}><Grid3X3 size={17}/>Portfolio<span>9</span></button><button id="projects-tab" role="tab" aria-selected={tab === 'projects'} aria-controls="profile-panel" className={tab === 'projects' ? 'active' : ''} onClick={() => setTab('projects')}><Layers size={18}/>Progetti<span>3</span></button></div><div id="profile-panel" role="tabpanel" aria-labelledby={tab === 'portfolio' ? 'portfolio-tab' : 'projects-tab'}>{tab === 'portfolio' ? <div className="portfolio-grid">{portfolio.map(item => <figure key={item.title}><img src={item.image} alt={item.title} loading="lazy"/><figcaption>{item.title}</figcaption></figure>)}</div> : <div className="project-list">{profileProjects.map((p, i) => <article className="profile-project" key={p.title}><img src={p.image} alt=""/><div><span className={`project-status status-${i}`}><span/>{p.status}</span><h2>{p.title}</h2><p>{p.description}</p></div></article>)}</div>}</div></section></>;
}
